[package]
name = "lcr-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
indicatif = {version = "0.17", features = ["rayon"]}
rand = "0.9"
rayon = "1.10.0"
